#!/usr/bin/env bash
# generate_virome_synthetic.sh — Generate minimal synthetic paired FASTQ files
# and a matching samplesheet.csv for virome pipeline testing.
#
# Usage:
#   generate_virome_synthetic.sh <output_dir> [num_reads]
#
#   output_dir  - Directory where synthetic FASTQs and samplesheet will be written.
#                 Defaults to $SCRATCH_ROOT/pipelines/virome/test_data
#                 (requires SCRATCH_ROOT to be set, e.g., source bin/lib/common.sh)
#   num_reads   - Number of read pairs per sample (default: 1000)
#
# Output layout:
#   <output_dir>/
#     fastq/
#       virome_sampleA_1.fastq.gz
#       virome_sampleA_2.fastq.gz
#       virome_sampleB_1.fastq.gz
#       virome_sampleB_2.fastq.gz
#     samplesheet.csv           columns: sample,fastq_r1,fastq_r2
#
# NOTE: A Kraken2 database is NOT generated here — Kraken2 databases are large
# (even the "viral only" set is ~5 GB). Options for Layer 3 virome testing:
#   Option A: Use the shared Juno Kraken2 DB at
#             /groups/tprice/pipelines/references/kraken2_viral_db
#   Option B: Build a tiny test DB (just a few viral genomes):
#             kraken2-build --download-taxonomy --db tiny_kraken2_db
#             kraken2-build --add-to-library viral_genome.fa --db tiny_kraken2_db
#             kraken2-build --build --db tiny_kraken2_db --threads 4
#             Place it at: $REPO_ROOT/references/tiny/kraken2_db

set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────
OUTPUT_DIR="${1:-}"
NUM_READS="${2:-1000}"

if [[ -z "$OUTPUT_DIR" ]]; then
    if [[ -n "${SCRATCH_ROOT:-}" ]]; then
        OUTPUT_DIR="$SCRATCH_ROOT/pipelines/virome/test_data"
    else
        printf '[ERROR] Usage: %s <output_dir> [num_reads]\n' "$(basename "$0")" >&2
        exit 1
    fi
fi

if [[ ! "$NUM_READS" =~ ^[0-9]+$ ]] || [[ "$NUM_READS" -lt 1 ]]; then
    printf '[ERROR] num_reads must be a positive integer, got: %s\n' "$NUM_READS" >&2
    exit 1
fi

READ_LEN=50
SAMPLES=(virome_sampleA virome_sampleB)
FASTQ_DIR="$OUTPUT_DIR/fastq"
SAMPLESHEET="$OUTPUT_DIR/samplesheet.csv"

printf '[INFO]  Output directory : %s\n' "$OUTPUT_DIR"
printf '[INFO]  FASTQ directory  : %s\n' "$FASTQ_DIR"
printf '[INFO]  Reads per sample : %s\n' "$NUM_READS"
printf '[INFO]  Samples          : %s\n' "${SAMPLES[*]}"

mkdir -p "$FASTQ_DIR"

# ── FASTQ generation helper ───────────────────────────────────────────────────
_gen_fastq() {
    local out="$1"
    local sample="$2"
    local readnum="$3"
    local nreads="$4"
    local rlen="$5"
    local qual
    qual=$(printf 'I%.0s' $(seq 1 "$rlen"))

    {
        local i
        for (( i = 1; i <= nreads; i++ )); do
            local seq
            seq=$(tr -dc 'ACGT' < /dev/urandom 2>/dev/null | head -c "$rlen")
            printf '@%s_r%d/%d\n%s\n+\n%s\n' "$sample" "$i" "$readnum" "$seq" "$qual"
        done
    } | gzip -c > "$out"
}

# ── Generate FASTQs for each sample ──────────────────────────────────────────
for sample in "${SAMPLES[@]}"; do
    r1_out="$FASTQ_DIR/${sample}_1.fastq.gz"
    r2_out="$FASTQ_DIR/${sample}_2.fastq.gz"

    if [[ -f "$r1_out" && -f "$r2_out" ]]; then
        printf '[INFO]  Skipping %s — files already exist\n' "$sample"
        continue
    fi

    printf '[INFO]  Generating %s R1 (%d reads, %d bp)...\n' "$sample" "$NUM_READS" "$READ_LEN"
    _gen_fastq "$r1_out" "$sample" 1 "$NUM_READS" "$READ_LEN"

    printf '[INFO]  Generating %s R2 (%d reads, %d bp)...\n' "$sample" "$NUM_READS" "$READ_LEN"
    _gen_fastq "$r2_out" "$sample" 2 "$NUM_READS" "$READ_LEN"
done

# ── Generate samplesheet.csv ──────────────────────────────────────────────────
printf '[INFO]  Writing samplesheet.csv -> %s\n' "$SAMPLESHEET"
printf 'sample,fastq_r1,fastq_r2\n' > "$SAMPLESHEET"
for sample in "${SAMPLES[@]}"; do
    r1="$FASTQ_DIR/${sample}_1.fastq.gz"
    r2="$FASTQ_DIR/${sample}_2.fastq.gz"
    printf '%s,%s,%s\n' "$sample" "$r1" "$r2" >> "$SAMPLESHEET"
done

# ── Summary ──────────────────────────────────────────────────────────────────
printf '\n[INFO]  Done. Files written:\n'
ls -lh "$FASTQ_DIR/"*.fastq.gz 2>/dev/null | awk '{printf "          %s  %s\n", $5, $NF}'
printf '          %s\n' "$SAMPLESHEET"

printf '\n[WARN]  Kraken2 database is NOT generated by this script.\n'
printf '        For Layer 3 virome testing, you need a Kraken2 DB. Options:\n'
printf '          A) Use the shared DB: /groups/tprice/pipelines/references/kraken2_viral_db\n'
printf '          B) Build a tiny DB (see comments in this script)\n'

printf '\n[INFO]  Next steps:\n'
printf '          1. Ensure a Kraken2 DB is available (see above)\n'
printf '          2. Run: tjp-test-suite --pipeline virome --layer 3\n'
printf '        Or use the samplesheet directly:\n'
printf '          tjp-launch virome --dev --config <your_virome_config.yaml>\n'
printf '          (set samplesheet: %s)\n' "$SAMPLESHEET"
